weights_path = "/userspace/dra/nsu-ai/team_code/models"
llava_weights = "/userspace/pva/weights/llava_next"
debug = False
flask_debug = False
weights_ruen = "/userspace/pva/weights/opusruen"
weights_enru = "/userspace/pva/weights/opusenru"
weights_ocr = "/userspace/pva/weights/ocr"
weights_whisper = "/userspace/pva/weights/whisper-medium"
weights_mistral = "/userspace/dra/nsu-ai/team_code/models/llm"
weights_phi3 = "/userspace/dra/nsu-ai/team_code/models/Phi-3-mini-4k-instruct"
load_one_peace = True
load_blit = True
load_ocr = True
load_sbert = True
# llm_type = "llava"
# llm_type = "mistral"
llm_type = "phi3"
