weights_path = "/userspace/dra/nsu-ai/team_code/models"
llava_weights = "/userspace/pva/weights/llava_next"
debug = False
flask_debug = False
weights_ruen = "/userspace/pva/weights/opusruen"
weights_enru = "/userspace/pva/weights/opusenru"
weights_ocr = "/userspace/pva/weights/ocr"
weights_whisper = "/userspace/pva/weights/whisper-medium"
load_one_peace = True
load_blit = True
load_ocr = True
load_sbert = True
llm_type = "llava" # or "mistral"
